### ISSUE TITLE
Passing account holder name to Stripe

### ISSUE THREAD

**Issue by mgcox2** [zyra/capacitor-stripe#2]
I've been using your Stripe Cordova plugin for some time now with great results. I'm in the process of migrating my app to Capacitor. I noticed that when requesting a bank account token, it appears the account holder name and account type aren't being passed to the Stripe API. Any plans on adding this in the future? Thanks in advance for your work on this.

**Comment by ihadeed** [comment]
Hey @mgcox2 

This was removed due to the latest Android SDK not accepting these details anymore. I will check with Stripe to see if there's an alternative method.

What are you using the tokenized bank account details for?

I think they are not required for Stripe Connect account updates since the account itself contains the account holder information. I'm just guessing there, since the dashboard "Add external account" form doesn't collect the account holder details.

**Comment by ihadeed** [comment]
`capacitor-stripe@0.4.1` should now save the account holder details

**Comment by mgcox2** [comment]
@ihadeed, I'm using the bank token to create a Stripe Connect account server-side at a later time. The implementation is similar to the Lyft example used in Stripe documentation. For some reason, if the token was created without an account holder name, it errors when I use the token to create the Connect account a couple of minutes later server-side. Something to the effect of "the account cannot be used as a deposit account, reason: missing account holder name". Thanks for your help on this! Will upgrade my plugin and try it again.
