### ISSUE TITLE
Name param doesnts return from Stripe.createCardToken method

### ISSUE THREAD

**Issue by san4ezgig** [zyra/capacitor-stripe#6]
Hello, i call method Stripe.createCardToken with current params
![image](https://user-images.githubusercontent.com/25607300/78019893-192ec300-7359-11ea-899b-35387c3c29cc.png) 
and card object returns without name param
![image](https://user-images.githubusercontent.com/25607300/78022855-56e21a80-735e-11ea-881e-a719ab29f2c9.png)

**Comment by ihadeed** [comment]
Stripe doesn't send that information back.

I would rather not manipulate any incoming data from their API. Maybe they aren't sending back that data since it contains PII.. no idea.

If you are sure that you want to re-use the "name" value for other purposes, you can just manually add the name to the object returned from the plugin.
